spring:
  application:
    name: minitasbd
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/minitas
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          batch_size: 30
        generate_statistics: false
        order_inserts: true
    hibernate:
      ddl-auto: none #update
  flyway:
    #enabled: false #comment
    baselineOnMigrate: true
    baselineDescription: baseline_migration
    baselineVersion: 1.0

#spring:
#  application:
#    name: ventas
#  datasource:
#    url: jdbc:mariadb://127.0.0.1:3308/minitas
#    username: root
#    password: finanz
#    driver-class-name: org.mariadb.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MariaDB103Dialect
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MariaDB103Dialect
#        temp:
#          use_jdbc_metadata_defaults: false
#        jdbc:
#          batch_size: 30
#        generate_statistics: false
#        order_inserts: true
#    hibernate:
#      ddl-auto: none #update
#  flyway:
#    #enabled: false #comment
#    baselineOnMigrate: true
#    baselineDescription: baseline_migration
#    baselineVersion: 1.0
